### ISSUE TITLE
Add range method

### ISSUE THREAD

**Issue by yckart** [andrepolischuk/land#8]
As we can land sections/elements, it would nice to be able to *ship* them back into space. Once one is landed, sometimes we have to send another out again...

To be a bit more specific, a `range` in which the interpolations occur, so a `start`- and `end`point, would make this neat API really powerful.

The example below is imperfect/incomplete, but clarifies what I mean:
```js
land('.section')
  .children('h2')
    .between('50%', '100%')
      .y(-50)
      .opacity(0)
      .scale(0.5)
  .children('img')
    .between(42, 1337)
      .x(50)
      .scale(0.5)
    .between('25%', '50%')
      .rotate(10);
```

A positive side effect would be that we result in less calls to DOM-related getters like `offsetTop` and `offsetHeight`. If a percentage value (`0%`-`100%`) is passed, its context is the window height, or maybe a third `base` parameter.

**Comment by andrepolischuk** [comment]
I don't want to complicate API unnecessarily. For example, you can pass a transform function for any property currently:

```js
land('.section')
  .children('h2')
    .y(function (progress) {
      return 1 - progress;
    })
    .opacity(function (progress) {
      return 0.5 * progress;
    });
```

This function receives `progress` of current section scroll as argument (in range `0...1`) and expects the return the transformed `progress`.

Will it solve your problem? Or do you steel need the `Children#between` method?

**Comment by yckart** [comment]
Sure, relying on functions for some properties could be helpful, at some point. However, if we would take mine example above, and use a function for each property with a condition in it, instead of the `between`-method, it would look really oversized.

While I like things simple too, I understand your thoughts to keep the code lightweight and clean, but I also like it when the usage of it would also not become overcomplicated ;)

**Comment by andrepolischuk** [comment]
Sorry, I don't have enough time. Happy to accept a PR if you add this.

**Comment by andrepolischuk** [comment]
I close this issue. But I will reopen this if you want to send pr.
